### PR TITLE
Update RandomListBlock.php

### PR DESCRIPTION
**Pull request by trichers**
If I want to show only ONE item, and I write in the block edit 1 as limit it saves always the number 3

### CODE REVIEW

**Comment by cmfcmf** [comment]
Hi @trichers, your changes aren't correct. You should rather change the `>` sign in both line 93 and 162 to `>=` and don't replace the 3 by 1. Could you try that instead please?

**Comment by trichers** [comment]
Thanks for the info. I´ve done it!

**Comment by cmfcmf** [comment]
And you don't need to change line 140 anymore, sorry that I forgot to tell.

**Comment by trichers** [comment]
ok, done

**Pull request closed without merging**
